#!/bin/bash

CompilerOptions="-DDFRE_OSX32 "
CompilerOptions+="-std=c++11 "
CompilerOptions+="-fno-exceptions -fno-asynchronous-unwind-tables "
CompilerOptions+="-fno-stack-protector "
CompilerOptions+="-m32 "
CompilerOptions+="-Wall -Werror -Wextra "
CompilerOptions+="-Wno-unused-parameter "

if [ "$1" == '--coverage' ]; then
    echo "To get a coverage report run: ./test_re && gcov tester.cpp"
    CompilerOptions+="-stdlib=libc++ "
    CompilerOptions+="-mmacosx-version-min=10.9 "
    CompilerOptions+="-fprofile-arcs -ftest-coverage -DNO_START "
else
    CompilerOptions+="-static "
    CompilerOptions+="-nostdlib "
    CompilerOptions+="-mmacosx-version-min=10.6 "
fi

clang++ ../code/osx32_start.S ../code/main.cpp $CompilerOptions -o re
clang++ ../code/osx32_start.S ../code/tests/tester.cpp -I../code $CompilerOptions -o test_re
